server:
  port: 8081
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/blackberry-pizzas"
    username: "postgres"
    password: "banco123"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "create-drop"